# voxel_down_sample_size:  0.02 # unit = [m]
# voxel_down_sample_size:  0.01 # unit = [m]
voxel_down_sample_size:  0.005 # unit = [m]
# voxel_down_sample_size:  0.003 # unit = [m]
# ---
normal_estimation:
  radius_neighbor_search: 0.1
  max_neighbor_number   : 30
  k_normals_consistent  : 10
