defaults:
  - option    : default_option
  - renderer  : default_renderer
  - viewer    : visual_viewer
  - camera    : arm_grasp
  - pre_grasp : default_pre_grasp
# ----------------------
env_name  : "ur5e_hand"
hand_name : "robotiq_2f85"

end_effector_name      : "palm"
end_effector_body_name : "palm"
end_effector_site_name : "attachment_site"
mocap_site_name        : "target"

hand_pose_offset_info:
  canonical_hand_single_xpos  : [0., 0., 0.4]
  canonical_hand_single_xquat : [1., 0., 0., 0.]

d_bias : 0.00

reaching_threshold:
  finger:
    # pos: 0.005
    # vel: 0.001
    velocity    : 0.001
    stable_time : 0.3


arm_body_names : [
    "shoulder_link",  # 1
    "upper_arm_link", # 2
    "forearm_link",   # 3
    "wrist_1_link",   # 4
    "wrist_2_link",   # 5
    "wrist_3_link",   # 6
]

arm_joint_names : [
    "shoulder_pan_joint",  # 1
    "shoulder_lift_joint", # 2
    "elbow_joint",         # 3
    "wrist_1_joint",       # 4
    "wrist_2_joint",       # 5
    "wrist_3_joint",       # 6
]

arm_actuator_names : [
  "shoulder_pan" , # 1
  "shoulder_lift", # 2
  "elbow"        , # 3
  "wrist_1"      , # 4
  "wrist_2"      , # 5
  "wrist_3"      , # 6
]

hand_joint_names : [
  "finger_joint2",
]

mocap:
  hand:
    body_name: "hand"
  fingertip_base:
    name           : "fingertip_base_mocap"
    geom_info_name : "fingertip_center"
    normal_gripper : [0, 1, 0] # direction of gripper aperture
  fingertip_transformed:
    name : "fingertip_transformed_mocap"
  object:
    name      : "object"
    resolution: 121
  correspondence:
    object:
      name : "object_correspondence_mocap"
    fingertip:
      name : "fingertip_correspondence_mocap"
    threshold : 1e5 #  0.1
  scale_param : 0.005



