defaults:
  - _self_
  - load          : ycb
  - pre_prosessing: default
  - generate      : default
# ------------------------------------------
model_name: "011_banana"
# ------------------------------------------

grasp:
  panda:
    n_approach: [0.5, -0.5, 1]
    gripper_pose:
      translation: [0.003877, -0.006059, -0.022305] # 2/3
      rotvec     : [0.        , 0.        , -0.7853981]

  ur5e:
    n_approach: [0, 0, 1]
    gripper_pose:
      translation: [0.025492, -0.015074, -0.021883] # 0/4
      rotvec     : [0.        , 0.        , -0.35]

  kuka:
    n_approach: [0, 0, 1]
    gripper_pose:
      translation: [0.003877, -0.006059, -0.022305] # 2/3
      rotvec     : [0.        , 0.        , -0.7853981]
