defaults:
  - _self_
  - load          : ycb
  - pre_prosessing: default
  - generate      : default
# ------------------------------------------
model_name: "035_power_drill"
# ------------------------------------------

grasp:
  panda:
    n_approach: [1, -1 , 0]
    gripper_pose:
      translation : [-0.018550, -0.002859, -0.070254] # 4/6
      rotvec      : [0, 0, -0.78]

  ur5e:
    n_approach: [1, -1 , 0]
    gripper_pose:
      translation : [-0.018550, -0.002859, -0.070254] # 4/6
      rotvec      : [0, 0, -0.78]

  kuka:
    n_approach: [0, 0, 1]
    gripper_pose:
      translation : [-0.004494, -0.011357, -0.116512] # 6/7
      rotvec      : [0, 0, -0.78]
