defaults:
  - _self_
  - load          : default
  - pre_prosessing: default
  - generate      : default
# ------------------------------------------
model_name: "box"
# ----
n_approach: [0, 0, 1] # case1
# ----
gripper_pose:
  translation : [0.015, 0.015, -0.05] # case1
  # rotvec      : [0.        , 0.        , 0.] # case1
  rotvec      : [0.       , 0.        , 0.] # case1
