defaults:
  - _self_
  - load          : custom
  - pre_prosessing: default
  - generate      : default

# ------------------------------------------
model_name: "custom_OldCamera"
# ------------------------------------------

grasp:
  panda:
    n_approach: [-0., -0.3, 1]
    gripper_pose:
      translation : [0.043807, 0.043129, -0.080673] # 7/8
      rotvec      : [0, 0,  1.57        ]

  ur5e:
    n_approach: [-0., -0.3, 1]
    gripper_pose:
      translation : [0.043807, 0.043129, -0.080673] # 7/8
      rotvec      : [0, 0,  1.57        ]

  kuka:
    n_approach: [0, 0, 1]
    gripper_pose:
      translation : [0.045767, 0.094906, -0.071206] # 4/5
      rotvec      : [0, 0, 1.57] # [0, 0,  1.57        ]
