defaults:
  - _self_
  - load          : custom
  - pre_prosessing: default
  - generate      : default

# ------------------------------------------
model_name: "custom_RubberDuck"
# ------------------------------------------

grasp:
  panda:
    n_approach: [0.3, 0.0,  1.0]
    gripper_pose:
      translation:   [0.067006, 0.037205, -0.078979]  # 1/4
      rotvec      : [0.        , 0.        ,0. ]

  ur5e:
    n_approach: [0.3, 0.0,  1.0]
    gripper_pose:
      translation:   [0.067006, 0.037205, -0.078979]  # 1/4
      rotvec      : [0.        , 0.        ,0. ]

  kuka:
    n_approach: [0., 0.0,  1.0]
    # n_approach: [1, 0.0,  0]
    gripper_pose:
      translation:   [0.067006, 0.037205, -0.118979]  # 1/4
      rotvec      : [0.        , 0,        0. ]
