defaults:
  - _self_
  - load          : observed
  - pre_prosessing: observed
  - generate      : default

# ------------------------------------------
model_name: "observed_OldCamera"
# ------------------------------------------

grasp:

  ur5e:
    n_approach: [-0., -0.3, 1]
    gripper_pose:
      translation : [0.021323, -0.003407, -0.079659]
      rotvec      : [0, 0,  1.57        ]
