defaults:
  - _self_
  - load          : observed
  - pre_prosessing: observed
  - generate      : default

# ------------------------------------------
model_name: "observed_Hammer"
# ------------------------------------------

grasp:

  ur5e:
    n_approach: [-0., -0.1, 1]
    gripper_pose:
      translation : [0.057737, 0.043700, -0.011303]
      rotvec      : [0, 0,  0.        ]
