defaults:
  - _self_
  - load          : observed
  - pre_prosessing: observed
  - generate      : default

# ------------------------------------------
model_name: "observed_Controller"
# ------------------------------------------

grasp:

  ur5e:
    n_approach: [0., 1., 1]
    gripper_pose:
      translation :  [0.009203, 0.026682, -0.019528]
      rotvec      : [0, 0, -1.9        ]
