defaults:
  - _self_
  - load          : observed
  - pre_prosessing: observed
  - generate      : default

# ------------------------------------------
model_name: "observed_T"
# ------------------------------------------

grasp:

  ur5e:
    n_approach: [-0., 0.0, 1]
    gripper_pose:
      translation : [0.002989, 0.012229, -0.036371]
      rotvec      : [0, 0,  1.57        ]
