defaults:
  - _self_
  - load          : observed
  - pre_prosessing: observed
  - generate      : default

# ------------------------------------------
model_name: "observed_Tape"
# ------------------------------------------

grasp:

  ur5e:
    n_approach: [0., -1., 1]
    gripper_pose:
      translation : [0.023290, -0.003123, -0.082819]
      rotvec      : [0, 0,  1.57        ]
