name    : "kuka"
# ------------------------------
distance_between_points : 0.002 # [m]
# ------------------------------
gripper_z_width : 0.11936467 # [m]
gripper_x_width : 0.0258 # [m]
# ------------------------------
d_min   : 0.000 # geomの初期位置依存
d_max   : 0.080 # geomの初期位置依存
d0      : 0.080 # geomの初期位置依存
